"""
Reads all CSVs from a folder and produces:
  1. sparsity vs avd ade plot
  2. correlation between sparse run and baseline (0 sparsity)

Template generated by Claude Sonnet 4.6
"""

import glob
import os
import itertools

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import re
from matplotlib.ticker import MultipleLocator

# ── CONFIG ────────────────────────────────────────────────────────────────────

DATA_FOLDER = "./quantized_results_all_clips_nvfp4/sparsity_data/"          # <-- change this to your folder path
CSV_PATTERN = "*.csv"          # matches any .csv in that folder
OUTPUT_DIR  = "./quantized_results_all_clips_nvfp4/sparsity_data/sparse_comparison_plots - jul_17"        # where to save the figures (set None to just show)
CUSTOM_COLOURS = [
    "#e6194b",  # red
    "#3cb44b",  # green
    "#4363d8",  # blue
    "#f58231",  # orange
    "#911eb4",  # purpleR[4]
    "#42d4f4",  # cyan
    "#f032e6",  # magenta
    "#bfef45",  # lime
    "#fabed4",  # pink
    "#1C5A53",  # teal
]

EXCLUDE_FILES = [
    #"sparsity_85.csv",
    #"sparsity_90.csv",
]
# ─────────────────────────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True) if OUTPUT_DIR else None
def sparsity_from_name(name):
    """Pull the integer sparsity level out of a run name like 'sparsity_75' -> 75."""
    m = re.search(r"(\d+)", name)
    if m is None:
        raise ValueError(f"Could not parse a sparsity value from run name '{name}'")
    return int(m.group(1))

# ── LOAD DATA ─────────────────────────────────────────────────────────────────
csv_files = sorted(glob.glob(os.path.join(DATA_FOLDER, CSV_PATTERN)))
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in '{DATA_FOLDER}'")

runs = {}
for path in csv_files:
    filename = os.path.basename(path)
    if filename in EXCLUDE_FILES:
        print(f"  Skipping excluded file '{filename}'")
        continue

    name = os.path.splitext(os.path.basename(path))[0]
    df = pd.read_csv(path)
    required = {"parquet_index", "ADE"}
    if not required.issubset(df.columns):
        print(f"  [skip] {name}: missing columns {required - set(df.columns)}")
        continue
    df = df.sort_values("parquet_index").reset_index(drop=True)
    runs[name] = df
    print(f"  Loaded '{name}' — {len(df)} rows")

if not runs:
    raise ValueError("No valid runs loaded.")

run_names = sorted(runs.keys(), key=sparsity_from_name)
n_runs    = len(run_names)


def finish(fig, filename):
    """ save the figure to OUTPUT_DIR."""
    if OUTPUT_DIR:
        out = os.path.join(OUTPUT_DIR, filename)
        fig.savefig(out, dpi=150, bbox_inches="tight")
        print(f"  Saved {out}")
        plt.close(fig)


 
# ── PLOT 1: SPARSITY vs AVERAGE ADE ───────────────────────────────────────────
sparsities = np.array([sparsity_from_name(n) for n in run_names])
mean_ades  = np.array([runs[n]["ADE"].mean() for n in run_names])
 
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(sparsities, mean_ades, "-", color="#888888", zorder=1)  # trend line
ax.scatter(sparsities, mean_ades, color=CUSTOM_COLOURS[4], s=70, zorder=2)
 # one x-tick at every sparsity value that actually exists
ax.set_xticks(sparsities)
# annotate each point with its mean ADE
for s, m in zip(sparsities, mean_ades):
    ax.annotate(f"{m:.3f}",
                xy=(s, m),
                xytext=(0, 8),               # 8 points above the marker
                textcoords="offset points",
                ha="center", fontsize=8)
    
ax.text(0.5, 0.95, "*value above each point is avg ADE",
        transform=ax.transAxes, ha="right", va="top",
        fontsize=8, color="#151212")

ax.set_xlabel("Sparsity (%)")
ax.set_ylabel("Average ADE")
ax.set_title("Average ADE vs Sparsity - nvfp4")
ax.grid(True, alpha=0.3)
ax.legend(fontsize=8)
finish(fig, "avg_ade_vs_sparsity.png")
 
# Print the raw numbers too
print("\n  Average ADE per run:")
for n, s, m in zip(run_names, sparsities, mean_ades):
    print(f"    sparsity {s:>3}%  ->  mean ADE = {m:.4f}")


# ── PLOT 2: PER-CLIP ADE — non-sparse (baseline) vs sparse ────────────────────
# baseline = the sparsity-0 run
baseline_name = next((n for n in run_names if sparsity_from_name(n) == 0), None)
if baseline_name is None:
    print("  [skip plot 2] no sparsity-0 (non-sparse) run found")
else:
    baseline = runs[baseline_name][["parquet_index", "ADE"]].rename(columns={"ADE": "ADE_base"})
    base_pct = sparsity_from_name(baseline_name)
    correlation_results = []

    for i, name in enumerate(run_names):
        if name == baseline_name:
            continue

        merged = pd.merge(
            baseline,
            runs[name][["parquet_index", "ADE"]].rename(columns={"ADE": "ADE_sparse"}),
            on="parquet_index",
        )

        # correlation coefficient
        corr = merged["ADE_base"].corr(merged["ADE_sparse"])
        correlation_results.append({ # append to save
            "sparsity": sparsity_from_name(name),
            "pearson_correlation": corr,
        })
        
        fig, ax = plt.subplots(figsize=(7, 7))
        ax.scatter(merged["ADE_base"], merged["ADE_sparse"],
                   s=25, alpha=0.6,
                   color=CUSTOM_COLOURS[4])

        # y = x reference line, sized to this plot's data
        lo = min(merged["ADE_base"].min(), merged["ADE_sparse"].min())
        hi = max(merged["ADE_base"].max(), merged["ADE_sparse"].max())
        ax.plot([lo, hi], [lo, hi], "--", color="black", linewidth=1, label="y = x (no change)")

        ax.xaxis.set_major_locator(MultipleLocator(2))   # a tick every 2 ADE
        ax.yaxis.set_major_locator(MultipleLocator(2))

        pct = sparsity_from_name(name)
        ax.set_xlabel(f"ADE - non-sparse baseline ({base_pct}%)")
        ax.set_ylabel(f"ADE - {pct}% sparse")
        ax.set_title(f"{pct}% sparse vs non-sparse - nvfp4")
        ax.set_aspect("equal", adjustable="box")
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8)
        ax.text(
            0.05, 0.95,
            f"Pearson r = {corr:.3f}",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=10,
            bbox=dict(facecolor="white", alpha=0.8, edgecolor="none")
        )
        finish(fig, f"per_clip_ade_{pct}_vs_baseline.png")
   
   # -------- Sparisty vs correlation ------
    fig, ax = plt.subplots(figsize=(7, 7))
    corr_df = pd.DataFrame(correlation_results)

    ax.plot(corr_df["sparsity"], corr_df["pearson_correlation"], "-", color="#888888", zorder=1)  # trend line
    ax.scatter(corr_df["sparsity"], corr_df["pearson_correlation"],s=25, alpha=1, color=CUSTOM_COLOURS[4])

    ax.set_xlabel(f"Sparsity amount (%)")
    ax.set_ylabel(f"Correlation Coefficient")
    ax.set_title(f"Correlation Coefficient vs Sparsity - nvfp4")
    ax.set_xticks(corr_df["sparsity"])

    min_spacing = 0.005  # minimum correlation difference between ticks
    y_ticks = []

    for corr in corr_df["pearson_correlation"]:
        if not y_ticks or abs(corr - y_ticks[-1]) >= min_spacing:
            y_ticks.append(corr)

    ax.set_yticks(y_ticks)

    finish(fig, f"correlation_vs_sparsity_nvfp4.png")
    
    # save correlation data
    corr_path = os.path.join(
        OUTPUT_DIR,
        "sparsity_vs_correlation_coefficients.csv"
    )
    corr_df.to_csv(corr_path, index=False)
    print(f"Saved {corr_path}")