"""
Reads all CSVs from a folder (one per run) and produces:
  1. Scatter plot  - minADE vs parquet_index, colour-coded by run
  2. Pairwise % error difference plots - all unique run pairs

Template generated by Claude Sonnet 4.6
"""

import glob
import os
import itertools

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

# ── CONFIG ────────────────────────────────────────────────────────────────────
DATA_FOLDER = "./quantized_results_all_clips_nvfp4/sparsity_data"          # <-- change this to your folder path
CSV_PATTERN = "*.csv"          # matches any .csv in that folder
OUTPUT_DIR  = "./quantized_results_all_clips_nvfp4/sparsity_data/sparse_comparison_plots"        # where to save the figures (set None to just show)
CUSTOM_COLOURS = [
    "#e6194b",  # red
    "#3cb44b",  # green
    "#4363d8",  # blue
    "#f58231",  # orange
    "#911eb4",  # purple
    "#42d4f4",  # cyan
    "#f032e6",  # magenta
    "#bfef45",  # lime
    "#fabed4",  # pink
    "#469990",  # teal
]

EXCLUDE_FILES = [
    "sparsity_85.csv",
    #"sparsity_90.csv",
]
# ─────────────────────────────────────────────────────────────────────────────

os.makedirs(OUTPUT_DIR, exist_ok=True) if OUTPUT_DIR else None

# ── LOAD DATA ─────────────────────────────────────────────────────────────────
csv_files = sorted(glob.glob(os.path.join(DATA_FOLDER, CSV_PATTERN)))
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in '{DATA_FOLDER}'")

runs = {}
for path in csv_files:
    filename = os.path.basename(path)
    if filename in EXCLUDE_FILES:
        print(f"  Skipping excluded file '{filename}'")
        continue

    name = os.path.splitext(os.path.basename(path))[0]
    df = pd.read_csv(path)
    required = {"parquet_index", "ADE"}
    if not required.issubset(df.columns):
        print(f"  [skip] {name}: missing columns {required - set(df.columns)}")
        continue
    df = df.sort_values("parquet_index").reset_index(drop=True)
    runs[name] = df
    print(f"  Loaded '{name}' — {len(df)} rows")

if not runs:
    raise ValueError("No valid runs loaded.")

run_names = list(runs.keys())
n_runs    = len(run_names)

# ── COLOUR PALETTE ────────────────────────────────────────────────────────────
colour_map = {name: CUSTOM_COLOURS[i % len(CUSTOM_COLOURS)] for i, name in enumerate(run_names)}


# ══════════════════════════════════════════════════════════════════════════════
# PLOT 1 – Scatter: minADE vs parquet_index, all runs overlaid
# ══════════════════════════════════════════════════════════════════════════════
#fig1, axes1 = plt.subplots(1, n_runs, figsize=(7 * n_runs, 5), sharey=True)

ncols = int(np.ceil(np.sqrt(n_runs)))
nrows = int(np.ceil(n_runs / ncols))

fig1, axes1 = plt.subplots(
    nrows,
    ncols,
    figsize=(7 * ncols, 5 * nrows),
    sharey=True,
    squeeze=False
)

if n_runs == 1:
    axes1 = [axes1]
axes1 = axes1.flatten()

for i, name in enumerate(run_names):
    ax = axes1[i]
    df = runs[name]
    avg = df["ADE"].mean()

    ax.scatter(
        df["parquet_index"], df["ADE"],
        label=name,
        color=colour_map[name],
        alpha=0.6,
        s=18,
        linewidths=0,
    )

    ax.set_title(f"{name}\navg ADE = {avg:.3f}", fontsize=12)
    ax.set_xlabel("parquet_index", fontsize=11)
    if i % ncols == 0:
        ax.set_ylabel("ADE", fontsize=11)
    ax.grid(True, alpha=0.3)

fig1.tight_layout()

if OUTPUT_DIR:
    out1 = os.path.join(OUTPUT_DIR, "scatter_all_runs.png")
    fig1.savefig(out1, dpi=150)
    print(f"\nSaved: {out1}")

# ══════════════════════════════════════════════════════════════════════════════
# PLOT 2 – Pairwise % error difference  (all unique pairs)
# ══════════════════════════════════════════════════════════════════════════════
BASELINE = "NON_SPARSE"  # must match the csv filename without extension
other_runs = [name for name in run_names if name != BASELINE]
pairs = [(BASELINE, name) for name in other_runs]

if len(pairs) == 0:
    print("Only one run found — no pairwise comparison possible.")
else:
    n_pairs = len(pairs)
    ncols   = min(n_pairs, 2)
    nrows   = (n_pairs + ncols - 1) // ncols

    fig2, axes = plt.subplots(nrows, ncols,
                              figsize=(7 * ncols, 4.5 * nrows),
                              squeeze=False, sharey=True)
    axes_flat = axes.flatten()

    for idx, (non_sparse, sparse) in enumerate(pairs):
        ax = axes_flat[idx]

        df_non_sparse = runs[non_sparse].set_index("parquet_index")["ADE"]
        df_sparse = runs[sparse].set_index("parquet_index")["ADE"]

        # align on shared parquet_index values
        common_idx = df_non_sparse.index.intersection(df_sparse.index)      
        if len(common_idx) == 0:
            ax.set_title(f"{non_sparse} vs {sparse}\n(no shared parquet_index)")
            continue

        non_sparse_df = df_non_sparse.loc[common_idx]
        sparse_df = df_sparse.loc[common_idx]

        # % error of b relative to a:  (b - a) / |a| * 100
        # guard against zero denominator
        abs_diff = sparse_df - non_sparse_df   # meters; +ve worse, -ve improved

        pos_mask = abs_diff > 0
        neg_mask = abs_diff <= 0
        # lo, hi = np.nanpercentile(abs_diff.values, [2, 98]) #98 percentile
        # ax.set_ylim(lo, hi)
        ax.set_ylim(-5, 10)
        # below 0 means improved so green, above 0 means worse so red
        ax.scatter(abs_diff.index[pos_mask], abs_diff.values[pos_mask],
                s=10, alpha=0.5, color="red")
        ax.scatter(abs_diff.index[neg_mask], abs_diff.values[neg_mask],
                s=10, alpha=0.5, color="green")
        ax.axhline(0, color="black", linewidth=0.8)

        
        baseline_avg = non_sparse_df.mean()
        sparse_avg = sparse_df.mean()
        mean_diff = abs_diff.mean() 

        ax.axhline(mean_diff, color="orange", linewidth=1.2,
           linestyle="--", label=f"signed ADE diff = {mean_diff:+.2f} metres")
        
        # legend-only entries (no line drawn) for the raw ADE means
        ax.plot([], [], ' ', label=f"baseline mean ADE = {baseline_avg:.3f} m")
        ax.plot([], [], ' ', label=f"{sparse} mean ADE = {sparse_avg:.3f} m")
        ax.legend(fontsize=8)

        ax.set_xlabel("parquet_index", fontsize=10)
        ax.set_ylabel(f"delta in ADE (m)", fontsize=10)
        ax.set_title(f"{sparse} vs {non_sparse} -  signed ADE difference (m)", fontsize=12)
        ax.grid(True, alpha=0.3, axis="y")

    # hide any unused subplot panels
    for idx in range(n_pairs, len(axes_flat)):
        axes_flat[idx].set_visible(False)

    fig2.suptitle(f"signed difference in ADE (m)", fontsize=14, y=1.01)
    fig2.tight_layout()

    if OUTPUT_DIR:
        out2 = os.path.join(OUTPUT_DIR, "pairwise_abs_diff.png")
        fig2.savefig(out2, dpi=150, bbox_inches="tight")
        print(f"Saved: {out2}")

